### ISSUE TITLE
nice lib, can I add subtitle files into playlist?

### ISSUE THREAD

**Issue by tronghieu60s** [ektotv/playlist#6]
i want to add subtitle to per video, it supported?

**Comment by evoactivity** [comment]
Hi @tronghieu60s, thanks for filing an issue :)

I'm not against this in theory but the only information I can find about including subtitles in a playlist file is for VLC and for HLS manifests. VLC only supports looking up local files on your machine, and I'm not interested in supporting HLS manifests with this library.

VLC
```
#EXTVLCOPT:sub-file=/only/supports/local/paths.srt
```

HLS manifest
```
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,LANGUAGE="en",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog",URI="subtitles_en.m3u8"
```

If you have information of a standard way to do this I could invesitgate adding support, but I can't find anything when searching myself.
